### ISSUE TITLE
[Feature Request] option to display pages instead of scrolling

### ISSUE THREAD

**Issue by mathelby** [Pool-Of-Tears/Myne#134]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

I prefer "page"-turning to scrolling when I read ebooks, but if this is an option in Myne I can't find it. 

### Describe the solution you'd like

I would love an option in the Settings menu to switch between displaying in pages and displaying in scrolling format.

### How will you/everyone benefit from this feature?

To me, pages are the main advantage all the various DRM/ad-ridden ebook readers have over Myne at the moment. This option would make switching away from those apps much smoother.

**Comment by starry-shivam** [comment]
The thing is, unlike typical ebook readers where each chapter is divided into multiple pages and users navigate between them horizontally, Myne simply divides the book into chapters and navigates through them vertically by scrolling. Therefore, there is no concept of pages here. That's why we have a progress bar at the top of the ebook reader to track the progress of specific chapters, as there are no pages to count in the first place.

**Comment by mathelby** [comment]
Ah, I see. Thank you anyway!
