### ISSUE TITLE
App crashes when loading book list after update to 1.1.0

### ISSUE THREAD

**Issue by BertrandTheHealer** [Pool-Of-Tears/Myne#14]
After update to 1.1.0, when opening the home page or a category page the loading spinner appears for a while then the app crashes. If I switch to the main category page, library page, or settings page quick enough the crash does not occur.

Android 13/One UI 5

**Comment by starry-shivam** [comment]
Hi! It seems like this issue is specific to samsung devices because someone else had also reported it few weeks ago, but unfortunately they didn't provided any logs and as i don't own any samsung devices myself i was not able to reproduce the error myself :(

Can you please try giving crash logs via ADB?
Here's the debug apk file for the current release:
https://send.vis.ee/download/d61ebc6763e95c98/#wloWqMsscyTREuZJGs-Jzw

Simply install it (uninstall current release build beforehand since this is unsigned apk), open it and let it crash one or two times, then grab logs by running
```
adb logcat --buffer=crash -d > logcat.txt
```
It should create a file named `logcat.txt` which you need to send here.

<b><i>In case you don't know how to install/use ADB lemme give you a quick guide.</b></i>

You can learn & download adb for your system by following [this](https://developer.android.com/studio/releases/platform-tools) link.

Please follow these steps to grab logs.
- enable developer options in your device, go to system > build number & tap continuously 7 times (process may vary between different manufacturers)
- go to developer options and enable USB debugging.
- connect your phone with your computer
- if you're using windows then go to folder in which you've downloaded adb and do shift + right click, a terminal prompt will get opened, enter `./adb logcat --buffer=crash -d > logcat.txt`, adb will make a file named `logcat` in same directory, then you can share that logcat file here. I know it sounds bit complicated but it's actually very simple.

Thanks!

**Comment by starry-shivam** [comment]
Closing due to no response from author, feel free to re-open if you're still there and/or facing this same issue.
