### ISSUE TITLE
Wrong list position

### ISSUE THREAD

**Issue by yanhaoSeven** [Pool-Of-Tears/Myne#153]
The home list slides, switches CustomBottomNavigationItem and then returns to the home page and finds that the list position starts from 0

**Comment by starry-shivam** [comment]
I don't understand what you mean. Could you please clarify? Also, could you follow the [issue template](https://github.com/Pool-Of-Tears/Myne/issues/new/choose) and reopen this issue with the appropriate details and information? Thanks!

**Comment by yanhaoSeven** [comment]
https://github.com/Pool-Of-Tears/Myne/assets/5484163/54570c07-248f-4eb0-94a4-8c290e493489

Slide the list in Categories to crime, then switch to Library, and then switch back to Categories. The position of the list is now animal.

**Comment by starry-shivam** [comment]
This seems like an expected behavior. It doesn't store the position or data of this screen in the backstack because it's not particularly long. Additionally, on most modern phones, screens are large enough that scrolling isn't required very often. Therefore, storing the state of the screen would seem like a waste of memory.

**Comment by yanhaoSeven** [comment]
But the HomeScreen page is the same.

**Comment by starry-shivam** [comment]
Yeah you're right, I'll try to fix the issue with homescreen in next release

**Comment by yanhaoSeven** [comment]
Thanks, I am also a jetpack compose beginner. Hope to learn more

**Comment by starry-shivam** [comment]
@yanhaoSeven I've released a [small update](https://github.com/Pool-Of-Tears/Myne/releases/tag/v3.5.1) to address this issue.
