### ISSUE TITLE
[Feature Request] Add File type like PDF and CBZ

### ISSUE THREAD

**Issue by Aarish97** [Pool-Of-Tears/Myne#187]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

It doesn't have an option to add PDF or CBZ file types.

### Describe the solution you'd like

I need this feature to add and read PDF or CBZ related books.

### How will you/everyone benefit from this feature?

Most people download PDF or CBZ type so they can easily add the file directly to the app and read. by that downloading people will be increased.

### Additional context

it's one of the features most people like.

**Comment by starry-shivam** [comment]
Myne is not built to be a PDF/CBZ reader; it was primarily built as a client for the Gutenberg library. The app didn't even have the ability to import external EPUB files a few versions ago. However, many people have requested this feature, and since we already had an EPUB parser in place to parse internal (Gutenberg) books for the inbuilt ebook reader, I thought it wouldn't hurt to allow users to import their external EPUB files as well. This way, they can be parsed with the same EPUB parser. So, in the last few versions, I have mostly worked on improving the EPUB parser to better support various types of EPUB files. However, parsing PDF/CBZ is a whole different story, as it was never designed to handle those formats and seems totally out of scope for the app's intended functionality.
