### ISSUE TITLE
[Bug]: Not Properly Importing

### ISSUE THREAD

**Issue by Solovertical** [Pool-Of-Tears/Myne#219]
### Steps to reproduce

From App
- Import ebook
- only show cover without anything

From Filemanger
- Directly open ebook
- Open properly with every content attached

### Expected behaviour

It should show content properly

### Actual behaviour

Not showing anything except Cover

### Device name

Xiaomi 11i

### Android version

14

### Myne version

4.1.0

**Comment by starry-shivam** [comment]
Please share the EPUB file you were having issues with so I can reproduce and investigate it properly. Although I understand what you probably mean, some screenshots of the issue would also be helpful.

**Comment by starry-shivam** [comment]
Thanks. The issue is that the EPUB file you shared only has its cover page in the TOC index and does not include any other chapters. When you import the book and open it in the internal reader, it parses the book based on TOC file references to correctly map the chapters. However, since the TOC file was invalid in this case and only included the cover page, the only thing shown was the cover image. It works when you open the book directly from, say, the file manager because in that case, it parses based on the spine tag in the EPUB manifest, i.e., literally parsing every file inside the archive without focusing much on chapter mapping. I think I need to add checks for handling edge cases like these and fall back to spine-based parsing when the TOC is empty or only contains one item.
