### ISSUE TITLE
Integrated e-reader - reading mode

### ISSUE THREAD

**Issue by Xoias** [Pool-Of-Tears/Myne#221]
The application is favoulous, but in my opinion, there is only one issue preventing it to ve perfect: the reading modality.
Instead to have to scroll up and down, could it be possible to add an option to be shown in pages which could be moved swiping left and right? This is a more natural e-book experience and bettee for reading, instead to have to be scrolling down the whole time and not focusing the eyes by page.
Keep the good job!

**Comment by starry-shivam** [comment]
Hello, first off, thanks for your kind words! Regarding the feature request, it has already been discussed several times, and I don't have any plans to work on it anytime soon. Vertical reading is an intentional design decision, and changing that would require more work than you might think, which I'd rather allocate elsewhere—like improving the reader menu and adding new options, which I'm currently working on for upcoming releases. For more information, please take a look at #195 and #134. Thank you for understanding.
