### ISSUE TITLE
book source：Add

### ISSUE THREAD

**Issue by Pantyhose-X** [Pool-Of-Tears/Myne#30]
https://archive.org/details/texts
https://openlibrary.org/

### Other
Suggest creating a group at https://rvlt.gg

**Comment by starry-shivam** [comment]
Thanks for the suggestions but i see few major problems which I'll write down below:

 1. There's no way to know for sure that if all of the books available on this archive is copyright free aswell (if they're not then the app may get banned from the Google Play Store due to DMCA issues).

 2. i wasn't able to find any kind of API and similar things to fetch books metadata, which means the only way to implement this is by scraping off the website which is needs lot of work and continuous maintenance as websites keep changing their frontend code and even sometimes add ways to restrict web scraping.
 
 Considering the above reasons i don't think it's worth the time and effort, sorry!

**Comment by Pantyhose-X** [comment]
> Thanks for the suggestions but i see few major problems which I'll write down below:
> 
> 1. There's no way to know for sure that if all of the books available on this archive is copyright free aswell (if they're not then the app may get banned from the Google Play Store due to DMCA issues).
> 2. i wasn't able to find any kind of API and similar things to fetch books metadata, which means the only way to implement this is by scraping off the website which is needs lot of work and continuous maintenance as websites keep changing their frontend code and even sometimes add ways to restrict web scraping.
> 
> Considering the above reasons i don't think it's worth the time and effort, sorry!

https://archive.org/details/texts  API https://archive.org/developers/index-apis.html
https://openlibrary.org/ API https://openlibrary.org/developers/api

**Comment by starry-shivam** [comment]
Thanks for linking the resources (I'll take a look), can you also verify my other point about books being copyright free?

**Comment by jujubeja** [comment]
Suggest add archive
Millions of free well organised books, please
All the books on the platform are free from copyright and are available in multiple formats.
