### ISSUE TITLE
Permission denied while creating a new PR

### ISSUE THREAD

**Issue by Dolanpls** [Pool-Of-Tears/Myne#37]
Hi,

I make the Spanish translations for the app but when I tried to push the changes, my push was rejected

```
remote: Permission to Pool-Of-Tears/Myne.git denied to Dolanpls.
fatal: unable to access 'https://github.com/Pool-Of-Tears/Myne.git/': The requested URL returned error: 403
```

I'm in a new branch called 'spanish-translation' so I'm not trying to push into 'main' directly

**Comment by starry-shivam** [comment]
@Dolanpls Hi! Thanks showing interest in contributing translations, it seems that you might've cloned this repository instead of making a fork and now you're trying to push using the locally cloned repository, to create a pull request properly, please fork this repository and commit your changes onto your forked-repository instead, after committing the changes you should be able to create a pull request using GitHub web UI.

**Comment by Dolanpls** [comment]
You were right 😅 now I could create the PR
Thanks!
