### ISSUE TITLE
[Feature Request] Add different sources for books

### ISSUE THREAD

**Issue by JakeDevs** [Pool-Of-Tears/Myne#66]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Gutenberg has a lack of selection

### Describe the solution you'd like

Add ability to use custom sources for books

### How will you/everyone benefit from this feature?

This will greatly increase the scope of the application

**Comment by starry-shivam** [comment]
Myne is primarily a Gutenberg client, i don't have plans to add other sources as of yet, although I may think about it in future, also allowing users to add custom sources isn't really possible because every website has different methods of accessing data, there isn't any universal method which works in all of them.

**Comment by Pantyhose-X** [comment]
There is a any universal method which works in all of them https://github.com/gedoor/legado/blob/master/English.md
